slam_toolbox:
  ros__parameters:

    # ==========================
    # ⚡ STABILITY SETTINGS ⚡
    # ==========================
    map_update_interval: 1.0 # Thora relax kiya
    transform_publish_period: 0.02
    
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    
    # ==========================
    # STANDARD SETTINGS
    # ==========================
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping 

    # Latency Handling
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    # Lidar Matching (Drift Killer)
    use_scan_matching: true
    use_scan_barycenter: true
    
    # Strict Penalties (To avoid jumping)
    distance_variance_penalty: 0.2
    angle_variance_penalty: 0.5
    minimum_distance_penalty: 0.5
    minimum_angle_penalty: 0.9

    # Scan Ranges
    max_laser_range: 12.0
    min_laser_range: 0.2
    resolution: 0.05

    # Process
    throttle_scans: 1
    map_publish_period: 1.0
    
    # Loop Closure (Map Fixing)
    do_loop_closing: true
    loop_search_space_dimension: 8.0
    correlation_search_space_dimension: 0.5
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_maximum_variance_fine: 0.2
    loop_match_minimum_response_fine: 0.45